### PR TITLE
Fix for issue#13

### PR DESCRIPTION
**Pull request by Seres67**
This PR should fix [issue#13](https://github.com/rusty-bits/OC-tool/issues/13), please test it and see if it does what is expected

### CODE REVIEW

**Comment by rusty-bits** [comment]
Your fix on line 144, quoting the "$COM" is definetly correct, but your fix on line 141

com="$com -e \"s#'$old '#'$new'#\""

where you escape the quotes breaks the build for me on darwin(macos) and linux(4.4.50)
I'm wondering what platform you're running OC-tool on? I'll need to either have it check and use your fix on that platform, or see if it will work with a different delimiter.

Can you try

com="$com -e s\|'$old '\|'$new'\|"

if that works for you I can merge your pull. It works for me on darwin and linux

**Comment by Seres67** [comment]
As I said in the issue, I'm on Catalina 10.15.3 (Hackintosh) using zsh as shell.
This doesn't work with MacOS sed.
I'll try running it on linux and I'll give you my feedback.

**Comment by Seres67** [comment]
Both fixes are working for me on linux (kernel 5.5.2).

**Comment by rusty-bits** [comment]
> As I said in the issue, I'm on Catalina 10.15.3 (Hackintosh) using zsh as shell

doh, I saw that and totally forgot

I just changed the sed to the -f option to use a command file in place of the -e option I was using
It works for me on macOS Mojave using zsh, but don't have access to Catalina until I'm home tonight
Tested on Linux and working there as well.
I pushed it to master on 65eaec9 if you get a chance and want to try before I get home

**Comment by Seres67** [comment]
> I pushed it to master on [65eaec9](https://github.com/rusty-bits/OC-tool/commit/65eaec93be3741bc1921000f23443e6a7e2ee48f) if you get a chance and want to try before I get home

This works for me on Catalina.

**Pull request closed without merging**
